# Introduction to NLP Fundatmentals in TensorFlow

NLP has the goal of deriving information out of natural language

Another common term for NLP problem is seq2seq

## Check for GPU

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


## Downloading helper function inside the folder


! wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

In [2]:
from helper_functions import unzip_data, create_tensorboard_callback, plot_loss_curves, compare_historys

## Get a text dataset

The dataset we're going ti be using is Kaggle's introduction to NLP dataset. A classification problem

[Competition Link](https://www.kaggle.com/competitions/nlp-getting-started/overview)

In [3]:
!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip

unzip_data('nlp_getting_started.zip')

--2024-03-12 11:10:55--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 2404:6800:4009:805::201b, 2404:6800:4009:806::201b, 2404:6800:4009:809::201b, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|2404:6800:4009:805::201b|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: 'nlp_getting_started.zip.1'

nlp_getting_started 100%[===================>] 593.11K  --.-KB/s    in 0.1s    

2024-03-12 11:10:55 (4.80 MB/s) - 'nlp_getting_started.zip.1' saved [607343/607343]



## Become one with the data

In [4]:
# Read thed data
import pandas as pd

train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [5]:
# Shuffle training dataframe
train_df_shuffled = train_df.sample(frac= 1, random_state= 42)

train_df_shuffled.head()

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0

In [6]:
test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [7]:
# How many examples of each class
train_df['target'].value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [8]:
# How may samples
len(train_df), len(test_df)

(7613, 3263)

In [9]:
# Let's visualise some random training examples
import random
random_index = random.randint(0, len(train_df) - 5)

for row in train_df_shuffled[['text', 'target']][random_index: random_index + 5].itertuples():
    _, text, target = row
    print(f"Target: {'Disaster' if target == 1 else 'Not a disaster'}")
    print(f"Text: {text}")
    print("----\n")


Target: Not a disaster
Text: Mike Magner Discusses A Trust Betrayed: http://t.co/GETBjip5Rh via @YouTube #military #veterans #environment
----

Target: Not a disaster
Text: Beware of your temper and a loose tongue! These two dangerous weapons combined can lead a person to the Hellfire #islam!
----

Target: Disaster
Text: Flood: Two people dead 60 houses destroyed in Kaduna: Two people have been reportedly killed and 60 houses ut... http://t.co/BDsgF1CfaX
----

Target: Disaster
Text: MH370: Aircraft debris found on La Reunion is from missing Malaysia Airlines ... - ABC Onlin... http://t.co/N3lNdJKYo3 G #Malaysia #News
----

Target: Not a disaster
Text: Whenever I have a meltdown and need someone @Becca_Caitlyn99 is always like 'leaving in 5' and I don't know how I got so lucky #blessed
----



### Split data into training and validation sets

In [10]:
from sklearn.model_selection import train_test_split

# Use train_test_split() to split the trianing data into train and validation dataset

train_sentences, val_sentences, train_labels, val_labels = train_test_split(train_df_shuffled['text'].to_numpy(), train_df_shuffled['target'].to_numpy(), test_size= 0.1, random_state= 42)

In [11]:
len(train_sentences), len(train_labels), len(val_sentences), len(val_labels)

(6851, 6851, 762, 762)

In [12]:
# Check the first 10 sentences
train_sentences[:10], train_labels[:10]

(array(['@mogacola @zamtriossu i screamed after hitting tweet',
        'Imagine getting flattened by Kurt Zouma',
        '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
        "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
        'Somehow find you and I collide http://t.co/Ee8RpOahPk',
        '@EvaHanderek @MarleyKnysh great times until the bus driver held us hostage in the mall parking lot lmfao',
        'destroy the free fandom honestly',
        'Weapons stolen from National Guard Armory in New Albany still missing #Gunsense http://t.co/lKNU8902JE',
        '@wfaaweather Pete when will the heat wave pass? Is it really going to be mid month? Frisco Boy Scouts have a canoe trip in Okla.',
        'Patient-reported outcomes in long-term survivors of metastatic colorectal cancer - British Journal of Surgery http://t.co/5Yl4DC1Tqt'],
       dtype=object),
 array([0,

## Converting text into numbers

When dealing with a text problem, one of the first things you'll have to do before you can build a model is to convert your text to nuumbers.

There are a few ways to do this:
* Tokenization
* Embedding

### Text vectorization (tokenization)

In [13]:
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization

# Use defalut TextVectorization parameter
text_vectorizer = TextVectorization(max_tokens= None, # how many words in vocab
                                    standardize= 'lower_and_strip_punctuation',
                                    split= 'whitespace',
                                    ngrams= None, # creates a group of words
                                    output_mode= 'int', # in which format the output should be
                                    output_sequence_length= None, # how long deos the output sequence should be of
                                    )

In [14]:
# Find the average number of tokens in the training tweets
round(sum([len(i.split()) for i in train_sentences]) // len(train_sentences))

14

In [15]:
# Setup text vectorization variables
max_vocab_length = 10000 # max number of words to have in our vocab
max_length = 15 # max length our sequences will be

text_vectorizer = TextVectorization(max_tokens= max_vocab_length,
                                    output_mode= 'int',
                                    output_sequence_length= max_length)

In [16]:
# Fit the text vectorization to training set
text_vectorizer.adapt(train_sentences)

In [17]:
# Create a sample sentence and tokenize it
sample_sentences = "There's a flood in my street!"

text_vectorizer([sample_sentences])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[264,   3, 232,   4,  13, 698,   0,   0,   0,   0,   0,   0,   0,
          0,   0]])>

In [20]:
# Choose a random sentences from the training sentences
random_sentences = random.choice(train_sentences)
print(f"Original text: {random_sentences}")
print(f"Vectorized sentence: {text_vectorizer([random_sentences])}")

Original text: -??-
; kitana
? her fatalities slay me
‰ÛÓkody? (Vine by @KOMBATFANS33) https://t.co/uMajwSNLUF
Vectorized sentence: [[   1   81  301 8417   31 6431 1927   18    1    1    0    0    0    0
     0]]


In [21]:
words_in_vocab = text_vectorizer.get_vocabulary() # retrieves all of the unique words

tope_5_words = words_in_vocab[:5] # gets the most common words
bottom_5_words = words_in_vocab[-5:] # gets the least common words

print(f"Number fo words in vocab: {len(words_in_vocab)}")
print(f"5 most common words: {tope_5_words}")
print(f"5 least common words: {bottom_5_words}")

Number fo words in vocab: 10000
5 most common words: ['', '[UNK]', 'the', 'a', 'in']
5 least common words: ['pages', 'paeds', 'pads', 'padres', 'paddytomlinson1']


### Creating an Embedding using an Embedding layer

We're going to use Tensorflow Embedding layer.


The parameters we care most about our embedding layers:
* `input_dim`
* `output_dim`
* `input_length`

In [23]:
from tensorflow.keras import layers

embedding = layers.Embedding(input_dim= max_vocab_length, # set input shape
                             output_dim= 128,
                             input_length= max_length # how long is each input
                             )

embedding

In [36]:
# Get a ranomd sentence from the training set
random_sentences = random.choice(train_sentences)

print(f"Original sentences: {random_sentences}")

# Embed the random sentences
sample_embde = embedding(text_vectorizer([random_sentences]))
sample_embde

Original sentences: that horrible sinking feeling when you‰Ûªve been at home on your phone for a while and you realise its been on 3G this whole time


<tf.Tensor: shape=(1, 15, 128), dtype=float32, numpy=
array([[[-0.043427  , -0.02271678, -0.00248923, ..., -0.03483094,
         -0.01346254, -0.03058391],
        [ 0.03267677,  0.04190341, -0.04285845, ...,  0.0135429 ,
         -0.02445282, -0.03918562],
        [ 0.01630927, -0.03321409, -0.00125452, ...,  0.02345994,
          0.02224901,  0.00741848],
        ...,
        [-0.02616034,  0.00962585,  0.0474998 , ...,  0.03219023,
          0.0456875 ,  0.04080323],
        [-0.01575265,  0.04413174,  0.01501777, ..., -0.04161366,
         -0.03297486,  0.00340591],
        [-0.01612275,  0.04820825,  0.0210881 , ...,  0.02680815,
          0.03131999, -0.00614514]]], dtype=float32)>

In [37]:
# Check out a single token's embedding
sample_embde[0][0], sample_embde[0][0].shape, random_sentences[0]

(<tf.Tensor: shape=(128,), dtype=float32, numpy=
 array([-0.043427  , -0.02271678, -0.00248923, -0.04603863,  0.00509753,
         0.01818783, -0.00246652,  0.01118038,  0.00157026,  0.04659058,
        -0.01123718, -0.00972148,  0.04788823,  0.01407531, -0.02020611,
        -0.03455592,  0.04628216, -0.04112779,  0.04135301, -0.02473733,
         0.03040474,  0.02041018,  0.00029361, -0.04249674,  0.0377947 ,
        -0.00522221,  0.03419198, -0.01971959,  0.02616808,  0.03351443,
        -0.0458042 , -0.02779064,  0.04195997, -0.02212015, -0.03683157,
         0.00789969,  0.02253792, -0.04799919, -0.03994947, -0.04821298,
        -0.04259375,  0.02873099,  0.03656069, -0.04618149, -0.04235861,
        -0.03062811,  0.02972574, -0.01694834,  0.03712305,  0.03289719,
         0.04936178, -0.01675064, -0.04377675,  0.02584152,  0.04081562,
        -0.00031313, -0.00864778, -0.00172927,  0.02708354, -0.0185649 ,
        -0.04001318,  0.00172317,  0.01937211,  0.00556774,  0.00397693,
  

## Modeling a text dataset

Experiments:

* Model 0: Naive Bayes
* Model 1: Feed-forward neural network
* Model 2: LSTM model
* Model 3: GRU model
* Model 4: Bidirectional LSTM model
* Model 5: 1D Convolutional Neural Network
* Model 6: Tensorflow Hub pretrained fetaure extractor
* Model 7: Same as Model 6 but with 10% of the data

### Model 0: Getting a baseline

> **Note**: It is common practice to use non-DL algorithm as a baseline because of their speed and then alter using DL to see if you can improve upon them

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Create tokenizer and modelling pipeline
model_0 = Pipeline([
    ("tfidf", TfidfVectorizer()), # convert the text data into numerical form using tf-idf technique
    ("clf", MultinomialNB()) # classifier for the text
])

# Fit the pipeline to the training data
model_0.fit(train_sentences, train_labels)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [40]:
# Evaluate our baseline model
baseline_score = model_0.score(val_sentences, val_labels)
print(f"Our baseline model achieves: {baseline_score * 100 :.2f}%")

Our baseline model achieves: 79.27%


In [42]:
# Make prediction
baseline_preds = model_0.predict(val_sentences)
baseline_preds[:20]

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1])

In [52]:
# Create an evaluation function to evaluate the model
# A function which returns a dictionary of accuracy, precision, recall and f1-score
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score

def evaluation(y_true, y_pred):
    '''
    This function gives the evaluation of the classification model in a dictionary form (Accuracy, Precision, Recall and F1-score)

    Parameters:
        y_true: The true labels of the evaluation data
        y_pred: The predicted labels of the evaluation data

    Returns:
        A dictionary with keys: `accuracy`, `precision`, `recall`, `f1-score`
    '''

    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1score = f1_score(y_true, y_pred, average= 'weighted') # we are using weighted  average because the dataset is slightly imbalanced

    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1-score': f1score
    }

In [84]:
baseline_results = evaluation(y_true= val_labels, 
           y_pred= baseline_preds)

### Model 1: A Simple dense model

In [54]:
# Create directory to save tensorboard callback logs
SAVED_DIR = "model_logs"

In [73]:
# Build model with the Functiobnal API

inputs = layers.Input(shape= (1, ), dtype= tf.string)
x = text_vectorizer(inputs) # convert text to numbers
x = embedding(x) # convert numbers to matrix
x = layers.GlobalAveragePooling1D(name= 'global_avg_pool_layer')(x)
outputs = layers.Dense(1, activation= 'sigmoid', name= 'output_layer')(x)

model_1 = tf.keras.Model(inputs, outputs, name= 'model_1_dense')

In [74]:
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_7 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (Text  (None, 15)                0         
 Vectorization)                                                  
                                                                 
 embedding (Embedding)       (None, 15, 128)           1280000   
                                                                 
 global_avg_pool_layer (Glo  (None, 128)               0         
 balAveragePooling1D)                                            
                                                                 
 output_layer (Dense)        (None, 1)                 129       
                                                                 
Total params: 1280129 (4.88 MB)
Trainable params: 128

In [75]:
# Compile the model
model_1.compile(loss= 'binary_crossentropy',
                optimizer= tf.keras.optimizers.legacy.Adam(),
                metrics= ['accuracy'])

In [76]:
model_1_history = model_1.fit(x = train_sentences,
                              y= train_labels,
                              epochs= 5,
                              validation_data= (val_sentences, val_labels),
                              callbacks= [create_tensorboard_callback(SAVED_DIR, 'model_1_dense')])

Saving TensorBoard log files to: model_logs/model_1_dense/20240312-130658
Epoch 1/5
215/215 [==============================] - 5s 16ms/step - loss: 0.6111 - accuracy: 0.6871 - val_loss: 0.5362 - val_accuracy: 0.7585
Epoch 2/5
215/215 [==============================] - 2s 10ms/step - loss: 0.4403 - accuracy: 0.8183 - val_loss: 0.4701 - val_accuracy: 0.7835
Epoch 3/5
215/215 [==============================] - 2s 10ms/step - loss: 0.3456 - accuracy: 0.8610 - val_loss: 0.4577 - val_accuracy: 0.7927
Epoch 4/5
215/215 [==============================] - 2s 9ms/step - loss: 0.2838 - accuracy: 0.8920 - val_loss: 0.4646 - val_accuracy: 0.7874
Epoch 5/5
215/215 [==============================] - 2s 11ms/step - loss: 0.2376 - accuracy: 0.9099 - val_loss: 0.4869 - val_accuracy: 0.7887


In [77]:
model_1.evaluate(val_sentences, val_labels)

24/24 [==============================] - 0s 5ms/step - loss: 0.4869 - accuracy: 0.7887


[0.4868801534175873, 0.7887139320373535]

In [79]:
model_1_preds = model_1.predict(val_sentences)
model_1_preds.shape

24/24 [==============================] - 0s 2ms/step


(762, 1)

In [83]:
model_1_results = evaluation(y_true= val_labels,
           y_pred= tf.round(tf.squeeze(model_1_preds)))

In [85]:
import numpy as np

np.array(list(model_1_results.values())) > np.array(list(baseline_results.values()))

array([False, False,  True, False])