# In this notebook, we are going to cover the fundamentals of tensorlfow

Outline:
1. Introduction to Tensors ✅
2. Getting information from tensors ✅
3. Manipulating Tensors✅
4. Tensors and Numpy
5. Using @tf.function (to speed up normal python functions)
6. Using GPUs or TPUs
7. Excercises

## Introduction to Tensors

In [46]:
#import tensorflow
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.11.0


In [2]:
#Create tensors with tf.constant()
scalar = tf.constant(7)

scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#Check the number of dimensions using ndim
scalar.ndim

0

In [4]:
#Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#Check the dimension of the vector

vector.ndim

1

In [6]:
#Create a matrix

matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [12]:
matrix.ndim

2

In [13]:
#Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype= tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
another_matrix.ndim

2

In [15]:
#Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                        [[13, 14, 15],
                         [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [16]:
tensor.ndim

3

What we have created so far:

1. Scalar: a single number
2. Vector: a number with direction
3. Matrix: a two dimensional array of numbers
4. Tensor: an n-dimensional array of numbers

### Creating tesnors with `tf.Variable`

In [18]:
#Create the same tensor with tf.Variable()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [19]:
#Let's change one of the elements
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [20]:
#Use .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [21]:
#Let's try to chnage unchangeable tensor
unchangeable_tensor[0] = 7
unchangeable_tensor

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [22]:
#Use .assign()
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Create Random tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [43]:
#Create two random tensors

random_1 = tf.random.Generator.from_seed(0)
random_1 = random_1.uniform([1])

random_1

: 

### Shuffle the order of elements in a tensor

In [2]:
#Shuffle a tensor

not_shufled = tf.constant([[10, 7],
                           [3, 4],
                           [2, 5]])

not_shufled.ndim

2

In [3]:
#Shuffle our non shuffled tensor
tf.random.shuffle(not_shufled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [15]:
tf.random.set_seed(42)
tf.random.shuffle(not_shufled, seed= 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

**Excercise**: Read through Tensorflow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed
Practice 5 random tensors shuffle

In [42]:
tf.random.set_seed(4)
tf.random.shuffle(not_shufled, seed= 7)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [2]:
#Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [3]:
#Create tensor of all zeros
tf.zeros(shape= (3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Converting Numpy arrays to tensor

Main difference between numpy arrays and tensorflow tensors is that tensors can be run on a GPU faster.

In [5]:
#Convert numpy to tensor
import numpy as np

numpy_A = np.arange(1, 25, dtype= np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [9]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

1. Shape
2. Rank
3. Axis or dimension
4. Size

In [11]:
#Create a rank 4 tensor 
rank_4_tensor = tf.zeros(shape= [2, 3, 4, 5])

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [12]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [20]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [21]:
#Get various attributes of our tensors
print(f"Datatype of every element: {rank_4_tensor.dtype}")
print(f"Number of dimensions(Rank): {rank_4_tensor.ndim}")
print(f"Shape of tensors: {rank_4_tensor.shape}")
print(f"Elements along the 0 axis: {rank_4_tensor.shape[0]}")
print(f"Element laong the last axis: {rank_4_tensor.shape[-1]}")
print(f"Total number of elements: {tf.size(rank_4_tensor).numpy()}")

Datatype of every element: <dtype: 'float32'>
Number of dimensions(Rank): 4
Shape of tensors: (2, 3, 4, 5)
Elements along the 0 axis: 2
Element laong the last axis: 5
Total number of elements: 120


### INdexing tensors

Tensors can be indexed just like python list

In [22]:
#Fet the first two elements of each dimensions
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [24]:
#Get the first element from each element from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
#Create a rank two tensor
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [28]:
#Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [31]:
#Add extra dimension

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [34]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis= -1) #-1 means final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [35]:
tf.expand_dims(rank_2_tensor, axis= 0) #expan axis in the 0th axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors
**Basic Operations**

`+`, `-`, `*`, `/`

In [3]:
#Addition
tensor = tf.constant([[10, 7], [3, 4]])

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [4]:
#Subtraction
tensor - 10 #this cannot be enabled on GPU

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
#We can use tensorflow nuilt-in function
tf.multiply(tensor, 10) #this can be enabled on GPU

**Matrix Multiplication**

In ML, matrix multiplication is one of the basic operation

In [6]:
#Matrix Multiplication
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [15]:
A = tf.constant([[1, 2, 5],
                 [7, 2, 1],
                  [3, 3, 3]])
B = tf.constant([[3, 5],
                 [6, 7],
                 [1, 8]])

print(f"{A} * {B} = {tf.matmul(A, B)}")
print(f"{A} @ {B} = {A @ B}")
print(f"{A @ B == tf.matmul(A, B)}")
print(f"{A} * {B} = {A * B}")

[[1 2 5]
 [7 2 1]
 [3 3 3]] * [[3 5]
 [6 7]
 [1 8]] = [[20 59]
 [34 57]
 [30 60]]
[[1 2 5]
 [7 2 1]
 [3 3 3]] @ [[3 5]
 [6 7]
 [1 8]] = [[20 59]
 [34 57]
 [30 60]]
[[ True  True]
 [ True  True]
 [ True  True]]


InvalidArgumentError: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [3,3] vs. [3,2] [Op:Mul]

In [16]:
#Matrix multiplication iwth Python operator @
A @ B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [17]:
tensor.shape

TensorShape([2, 2])

In [18]:
#Create a tensor of (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [24]:
#Try matrix multiplication with same shape
print(f"Mutiplication transposing Y: {tf.matmul(X, tf.transpose(Y))}")
print(f"Multiplication transposing X: {tf.matmul(tf.transpose(X), Y)}")

Mutiplication transposing Y: [[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]]
Multiplication transposing X: [[ 89  98]
 [116 128]]


**The dot product**

Matrix Multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
1. `tf.matmul()`
2. `tf.tensordot()`

In [28]:
#Perform dot product on X and Y (transposing is required)
tf.tensordot(X, tf.transpose(Y), axes= 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [33]:
#Perform matrix multiplication between X and Y (reshape)

tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [30]:
#Check values of Y, reshape and transpose

print("Priginal Y: ")
print(f"{Y} \n")

print("Reshaped Y: ")
print(f"{tf.reshape(Y, shape= (2, 3))} \n")

print("Transposed Y: ")
print(f"{tf.transpose(Y)}")

Priginal Y: 
[[ 7  8]
 [ 9 10]
 [11 12]] 

Reshaped Y: 
[[ 7  8  9]
 [10 11 12]] 

Transposed Y: 
[[ 7  9 11]
 [ 8 10 12]]


### Changing the datatyype of a tensor

In [36]:
#Create a new tensor with default datatype

B = tf.constant([1.7, 7.4])

B.dtype

tf.float32

In [37]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [39]:
D = tf.cast(B, dtype= tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

### Aggregating Tensors

Aggregating tensors = condensing them from multiple values to smaller amount of values

In [43]:
#Get the absolute value
E = tf.constant([-7, -10])
E

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [44]:
tf.abs(E)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following form of aggregation

1. Minimum
2. Maximum
3. Mean of the tensor
4. Sum of the tensor

In [52]:
F = tf.constant(np.random.randint(0, 100, size= 50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([86, 50, 10, 34, 96, 30, 61, 66, 31, 36, 53, 76, 72, 93, 69, 84, 35,
       94, 81, 59, 30,  6, 59, 63,  2, 87,  7, 14,  2, 38, 82, 65, 46, 20,
       82, 34, 24, 60, 36, 89, 49, 32, 94, 34, 38, 49, 18, 87, 12, 48])>

In [53]:
tf.size(F), F.shape, F.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [54]:
#Minimum
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [55]:
#Maximum
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [56]:
#Mean
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [57]:
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2523>

**Excercise**:
1. Find the variance and the standard deviation

In [63]:
#Variance
tf.math.reduce_variance(tf.cast(F, dtype= tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=772.0>

In [64]:
#Standard Deviation
tf.math.reduce_std(tf.cast(F, dtype= tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=27.78>

In [126]:
#Alternative method
import tensorflow_probability as tfp
F = tf.constant(np.random.randint(0, 100, size= 50))
F

print(f"Variance: {tfp.stats.variance(F)}")
print(f"Stnadard Deviatrion: {tfp.stats.stddev(tf.cast(F, dtype= tf.float32))}")

Variance: 963
Stnadard Deviatrion: 31.038040161132812


### Find the positional maximum and minimum

In [86]:
#Creating a new ternsor
np.random.seed(42)
G = tf.constant(np.random.randn(50))
G

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
       -0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
       -0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ,
        1.46564877, -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272,
        0.11092259, -1.15099358,  0.37569802, -0.60063869, -0.29169375,
       -0.60170661,  1.85227818, -0.01349722, -1.05771093,  0.82254491,
       -1.22084365,  0.2088636 , -1.95967012, -1.32818605,  0.19686124,
        0.73846658,  0.17136828, -0.11564828, -0.3011037 , -1.47852199,
       -0.71984421, -0.46063877,  1.05712223,  0.34361829, -1.76304016])>

In [95]:
H = tf.reshape(G, shape=(2, 25))
H

<tf.Tensor: shape=(2, 25), dtype=float64, numpy=
array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
        -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
        -0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
        -0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ,
         1.46564877, -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272],
       [ 0.11092259, -1.15099358,  0.37569802, -0.60063869, -0.29169375,
        -0.60170661,  1.85227818, -0.01349722, -1.05771093,  0.82254491,
        -1.22084365,  0.2088636 , -1.95967012, -1.32818605,  0.19686124,
         0.73846658,  0.17136828, -0.11564828, -0.3011037 , -1.47852199,
        -0.71984421, -0.46063877,  1.05712223,  0.34361829, -1.76304016]])>

In [99]:
#Positional Maximum
print(f"Positional Maximum: {tf.argmax(H)}")
#print(tf.reduce_max(G) == G[tf.argmax(G)])

Positional Maximum: [0 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1 1 0 1 0 0 0 1 1 0]


In [101]:
#Positional Minimum
print(f"Positional Minimum: {tf.argmin(H, axis= 1)}")
print(tf.reduce_min(G) == G[tf.argmin(G)])

Positional Minimum: [13 12]
tf.Tensor(True, shape=(), dtype=bool)


In [104]:
H = tf.reshape(H, shape=(1, 1, 1, 1, 50))
H

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float64, numpy=
array([[[[[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986,
           -0.23415337, -0.23413696,  1.57921282,  0.76743473,
           -0.46947439,  0.54256004, -0.46341769, -0.46572975,
            0.24196227, -1.91328024, -1.72491783, -0.56228753,
           -1.01283112,  0.31424733, -0.90802408, -1.4123037 ,
            1.46564877, -0.2257763 ,  0.0675282 , -1.42474819,
           -0.54438272,  0.11092259, -1.15099358,  0.37569802,
           -0.60063869, -0.29169375, -0.60170661,  1.85227818,
           -0.01349722, -1.05771093,  0.82254491, -1.22084365,
            0.2088636 , -1.95967012, -1.32818605,  0.19686124,
            0.73846658,  0.17136828, -0.11564828, -0.3011037 ,
           -1.47852199, -0.71984421, -0.46063877,  1.05712223,
            0.34361829, -1.76304016]]]]])>

In [105]:
G.shape

TensorShape([50])

In [107]:
H_squeezed = tf.squeeze(H)
H_squeezed, H_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float64, numpy=
 array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
        -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
        -0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
        -0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ,
         1.46564877, -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272,
         0.11092259, -1.15099358,  0.37569802, -0.60063869, -0.29169375,
        -0.60170661,  1.85227818, -0.01349722, -1.05771093,  0.82254491,
        -1.22084365,  0.2088636 , -1.95967012, -1.32818605,  0.19686124,
         0.73846658,  0.17136828, -0.11564828, -0.3011037 , -1.47852199,
        -0.71984421, -0.46063877,  1.05712223,  0.34361829, -1.76304016])>,
 TensorShape([50]))

### One-hot Encoding

In [109]:
#Create a list of indices
some_ist = [e for e in range(0, 4)]

tf.one_hot(some_ist, depth= 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [113]:
#Specify custom values for one hot encoding
tf.one_hot(some_ist, depth= 2)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

### `Squaring`, `log`, `Square Root`

In [115]:
#Create a new tensor
I = tf.range(1, 10)
I

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [117]:
#Square
tf.square(I)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [120]:
#Find the square root
tf.sqrt(tf.cast(I, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [122]:
#Find the log
tf.math.log(tf.cast(I, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

Tensorflow interacts beautifully with Numpy arrays

**Note**: Main difference betweem a tensor and a Numpy Array is that a tensor can be used in GPU or TPU for faster process

In [123]:
#Create a tensor directly from a Numpy Array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [124]:
#Convert tensor to numpy arrays
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [125]:
#Convert tensor to a numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [127]:
#The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

#Check the data type of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [131]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

**Note**: If you have an access to a CUDA-enabled GPU, tensorflow will automatically use it whenever required