In [8]:
import tensorflow as tf
import numpy as np

### 1. Create a vector, scalar, matrix, and tensor with values of your choosing using `tf.constant()`

In [4]:
#Creation of vector
vector = tf.constant([1, 2, 3])
scalar = tf.constant(1)
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                       [7, 8, 9]])
tensor = tf.constant([[[1, 2],
                       [3, 4]],
                       [[5, 6],
                        [7, 8]],
                        [[9, 10],
                          [11, 12]]])

print(f"Vector {vector}")
print(f"Scalar {scalar}")
print(f"Matrix {matrix}")
print(f"Tensor {tensor}")

Vector [1 2 3]
Scalar 1
Matrix [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### 2. Find the shape, rank and size of the tensors you created in 1

In [7]:
print(f"Tensor shape: {tensor.shape}")
print(f"Tensor rank: {tensor.ndim}")
print(f"Tensor size: {tf.size(tensor)}")

Tensor shape: (3, 2, 2)
Tensor rank: 3
Tensor size: 12


### 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`

In [12]:
X = tf.constant(np.random.randn(5, 300))
Y = tf.constant(np.random.randn(5, 300))
X.shape, Y.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

### 4. Multiply the twwo tensors you created in 3 using matrix multiplication.

In [13]:
#Matrix Multiplication
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ -4.53953743,  -3.99164596,  41.13989288,   2.70817144,
        -15.44576529],
       [-20.1113261 ,  10.43977291,   9.595021  ,  -5.24671388,
        -23.68975812],
       [  8.31322284,  16.6807504 ,  -9.62543164,  14.65607743,
          9.80823006],
       [ 39.62254079,  -8.27219899,  -8.73986133,  14.45555883,
         -1.81130147],
       [-31.33507718,  17.2895949 ,  10.2673729 , -25.87047936,
          1.28784204]])>

### 5. Multipy two tensors you created in 3 using dot product

In [16]:
#Dot Product
tf.tensordot(X, Y, axes= 0)

<tf.Tensor: shape=(5, 300, 5, 300), dtype=float64, numpy=
array([[[[-1.68909823e+00,  1.00549782e+00,  1.28646938e+00, ...,
          -2.31548241e-01, -5.65498973e-01,  1.86116693e+00],
         [-9.71911028e-01, -2.22508370e-01,  1.01241162e+00, ...,
          -1.13710327e+00,  1.50579586e+00,  8.57240404e-01],
         [ 3.02520846e-02, -3.02730435e-01, -8.69956283e-01, ...,
          -3.32902118e-01,  4.54781900e-01, -4.22565790e-01],
         [ 6.99231390e-01, -5.18495038e-01, -9.84497417e-01, ...,
          -2.51075188e-01,  8.82480703e-02,  7.61354475e-01],
         [ 1.97708561e+00,  8.54174094e-02, -7.18710853e-01, ...,
           2.16664259e-01, -1.46316877e+00, -1.83786252e-01]],

        [[ 4.31408110e-01, -2.56811537e-01, -3.28573739e-01, ...,
           5.91391234e-02,  1.44432596e-01, -4.75355719e-01],
         [ 2.48233224e-01,  5.68302739e-02, -2.58577372e-01, ...,
           2.90424537e-01, -3.84591334e-01, -2.18945503e-01],
         [-7.72660487e-03,  7.73195793e-02, 

### 6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`

In [17]:
Z = tf.constant(np.random.randn(224, 224, 3))
Z.shape

TensorShape([224, 224, 3])

### 7. Find the min and max values of the tensor you created in 6 along the first axis

In [20]:
print(f"Min along first axes: {tf.reduce_min(Z, axis= 1)}")
print(f"Maximum along first axis: {tf.reduce_max(Z, axis= 1)}")

Min along first axes: [[-3.30979367 -3.02236501 -3.34211966]
 [-3.26627793 -2.79042312 -3.22811999]
 [-3.45768354 -2.35819853 -2.55726351]
 [-2.92328578 -2.33216502 -2.95323728]
 [-2.72103255 -2.18872514 -2.30957814]
 [-2.94047426 -2.44668376 -2.91179684]
 [-2.44130924 -2.87024986 -2.13935272]
 [-2.93431571 -2.86128393 -3.63543184]
 [-3.29682262 -2.98207447 -2.58110781]
 [-3.28318251 -2.04446053 -2.68022489]
 [-2.66209383 -2.87087617 -2.5045946 ]
 [-3.56511354 -3.1096081  -2.95934469]
 [-2.75551793 -2.27301324 -3.61468223]
 [-2.68705213 -2.92540386 -2.59434904]
 [-2.56333448 -3.06922647 -2.67862217]
 [-2.71102502 -2.69756493 -2.49065841]
 [-2.84852376 -2.85739367 -2.70675925]
 [-1.91936377 -2.71065745 -2.28890988]
 [-2.67487517 -2.13792144 -2.90656601]
 [-2.85561744 -2.37939223 -2.54645031]
 [-2.8662274  -2.61896641 -2.37275343]
 [-2.66215    -2.54151672 -3.00485022]
 [-2.28305821 -2.8112353  -3.25053742]
 [-2.58682923 -3.22585335 -2.69849115]
 [-3.39758675 -3.3221777  -2.48198602]
 [-

### 8. Create a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`

In [21]:
A = tf.constant(np.random.randn(1, 224, 224, 3))
A.shape

TensorShape([1, 224, 224, 3])

In [22]:
A_squeezed = tf.squeeze(A)
A_squeezed.shape

TensorShape([224, 224, 3])

### Create a tensor with shape `[10]` using you own choice of values, then find the index which has the maximum value

In [23]:
B = tf.constant([e for e in range(10)])
B.shape

TensorShape([10])

In [24]:
print(f"Positional maximum: {tf.argmax(B)}")

Positional maximum: 9


In [25]:
tf.one_hot(B, depth= 5)

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>